name: PHP Composer

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Symfony Requirements Check
      run: vendor/bin/requirements-checker

    - name: Build test suite
      run: composer run-script test build

    - name: Create database
      run: bin/console doctrine:database:create --env=test

    - name: Update database schema
      run: bin/console doctrine:schema:update --force --env=test

    - name: Validate database schema
      run: bin/console doctrine:schema:validate --skip-sync --env test

    - name: Database Migrations up-to-date
      run: bin/console doctrine:migrations:up-to-date --env test

    - name: Run test suite

      run: composer run-script test run

    - name: PHP Metrics Report
      run: vendor/bin/phpmetrics --plugins=symfony .

    # - name: Check CS
    #   run: vendor/bin/php-cs-fixer fix -v --dry-run --diff-format=udiff